int main();
int operations(int);
int compression();
int decompression();
char *create_masterarray(int);
int codelength(int);
int openfile();
int unique_char(int, char *);
char *insert_char(int, char *);
int preserve_ma( char *);
int compress(int,int,char *);
int decompress(int,char *);
int findloc(char ,char *);
int compress2(int, char *);
int compress2(int, char *);
int compress3(int, char *);
int compress4(int, char *);
int compress5(int, char *);
int compress6(int, char *);
int compress7(int, char *);
int decompress2(char *);
int decompress3(char *);
int decompress4(char *);
int decompress5(char *);
int decompress6(char *);
int decompress7(char *);
